# Generated by Django 5.0.6 on 2024-06-01 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('cantidad_habitaciones', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manager.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('categoria', models.CharField(choices=[('ECONOMICA', 'ECONOMICA'), ('SUIETE_JR', 'SUIETE_JR'), ('SUITEPRESIDENCIAL', 'SUITEPRESIDENCIAL')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('OCUPADA', 'OCUPADA'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('RESERVADA', 'RESERVADA')], max_length=20)),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manager.piso')),
            ],
        ),
    ]
