# Generated by Django 5.0.6 on 2024-06-03 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0002_rename_hostorial_historial'),
        ('hotel_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConogramaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_manager.cliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manager.habitacion')),
            ],
        ),
    ]
