# Generated by Django 5.0.6 on 2024-06-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manager', '0002_hotel_numhabitaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
