# Generated by Django 5.0.6 on 2024-06-04 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rename_dni_persona_documento_persona_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalHotel',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.persona')),
                ('salarioHora', models.FloatField()),
                ('horasTrabajadas', models.FloatField()),
            ],
            bases=('core.persona',),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'LUNES'), ('MARTES', 'MARTES'), ('MIERCOLES', 'MIERCOLES'), ('JUEVES', 'JUEVES'), ('VIERNES', 'VIERNES'), ('SABADO', 'SABADO'), ('DOMINGO', 'DOMINGO')], max_length=10)),
                ('turno', models.CharField(choices=[('MATUTINO', 'MATUTINO'), ('VESPERTINO', 'VESPERTINO'), ('NOCTURNO', 'NOCTURNO')], max_length=10)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('personalhotel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminHotel.personalhotel')),
            ],
            bases=('adminHotel.personalhotel',),
        ),
        migrations.CreateModel(
            name='CamareroPiso',
            fields=[
                ('personalhotel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminHotel.personalhotel')),
            ],
            bases=('adminHotel.personalhotel',),
        ),
        migrations.CreateModel(
            name='CamareroRestaurante',
            fields=[
                ('personalhotel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminHotel.personalhotel')),
            ],
            bases=('adminHotel.personalhotel',),
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('personalhotel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminHotel.personalhotel')),
            ],
            bases=('adminHotel.personalhotel',),
        ),
        migrations.AddField(
            model_name='personalhotel',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHotel.turno'),
        ),
    ]
