# Generated by Django 5.0.6 on 2024-06-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHotel', '0002_remove_personalhotel_persona_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camarerorestaurante',
            name='personalhotel_ptr',
        ),
        migrations.RemoveField(
            model_name='camareropiso',
            name='personalhotel_ptr',
        ),
        migrations.RemoveField(
            model_name='recepcionista',
            name='personalhotel_ptr',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='personalhotel_ptr',
        ),
        migrations.AddField(
            model_name='administrador',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='direccion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='documento',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='fecha_nacimiento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='horasTrabajadas',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='salarioHora',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminHotel.turno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='direccion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='documento',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='fecha_nacimiento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='horasTrabajadas',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='salarioHora',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='telefono',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camareropiso',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminHotel.turno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='direccion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='documento',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='fecha_nacimiento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='horasTrabajadas',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='salarioHora',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='telefono',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camarerorestaurante',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminHotel.turno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='direccion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='documento',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='fecha_nacimiento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='horasTrabajadas',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='salarioHora',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='telefono',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminHotel.turno'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PersonalHotel',
        ),
    ]
