# Generated by Django 5.0.6 on 2024-06-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHotel', '0003_remove_camarerorestaurante_personalhotel_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='camareropiso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='camarerorestaurante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recepcionista',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
