# Generated by Django 5.0.6 on 2024-06-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHotel', '0004_alter_administrador_id_alter_camareropiso_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camareropiso',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='camarerorestaurante',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='recepcionista',
            name='turno',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='CamareroPiso',
        ),
        migrations.DeleteModel(
            name='CamareroRestaurante',
        ),
        migrations.DeleteModel(
            name='Recepcionista',
        ),
    ]
