# Generated by Django 5.0.6 on 2024-06-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('RECEPCIONISTA', 'RECEPCIONISTA'), ('CAMARERO', 'CAMARERO'), ('LIMPIEZA', 'LIMPIEZA'), ('CLIENTE', 'CLIENTE')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
