# Generated by Django 5.0.6 on 2024-06-03 02:54

import datetime
import django.db.models.deletion
import recepcion_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminHotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('nombreRecepcionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHotel.recepcionista')),
            ],
            bases=(recepcion_panel.models.GestionReserva, models.Model),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('dias_hospedaje', models.IntegerField()),
                ('servicios_adicinales', models.CharField(max_length=100)),
                ('total', models.FloatField()),
                ('panelGestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion_panel.panelgestion')),
            ],
        ),
    ]
