# Generated by Django 5.0.6 on 2024-06-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hostorial',
            new_name='Historial',
        ),
    ]
