# Generated by Django 5.0.6 on 2024-06-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0002_cuentacliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
