<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> f6d1e94 (ViewsTemplates)
# Generated by Django 5.0.6 on 2024-06-03 02:09
=======
# Generated by Django 5.0.6 on 2024-06-04 06:10
>>>>>>> b2277ad (ViewsTemplates)
<<<<<<< HEAD
=======
# Generated by Django 5.0.6 on 2024-06-04 06:10
>>>>>>> b2277ad (ViewsTemplates)
=======
>>>>>>> f6d1e94 (ViewsTemplates)
=======
# Generated by Django 5.0.6 on 2024-06-04 06:10
>>>>>>> b2277ad (ViewsTemplates)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> f6d1e94 (ViewsTemplates)
        ('client_manager', '0002_rename_hostorial_historial'),
        ('hotel_manager', '0002_conogramareserva'),
=======
        ('hotel_manager', '0003_habitacion_disponible'),
        ('user_manager', '0002_cuenta_tipo'),
>>>>>>> b2277ad (ViewsTemplates)
<<<<<<< HEAD
=======
        ('hotel_manager', '0003_habitacion_disponible'),
        ('user_manager', '0002_cuenta_tipo'),
>>>>>>> b2277ad (ViewsTemplates)
=======
>>>>>>> f6d1e94 (ViewsTemplates)
=======
        ('hotel_manager', '0003_habitacion_disponible'),
        ('user_manager', '0002_cuenta_tipo'),
>>>>>>> b2277ad (ViewsTemplates)
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> f6d1e94 (ViewsTemplates)
            name='ServicioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
=======
<<<<<<< HEAD
=======
>>>>>>> b2277ad (ViewsTemplates)
=======
>>>>>>> f6d1e94 (ViewsTemplates)
=======
>>>>>>> b2277ad (ViewsTemplates)
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=20)),
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> b2277ad (ViewsTemplates)
=======
=======
>>>>>>> f6d1e94 (ViewsTemplates)
>>>>>>> b2277ad (ViewsTemplates)
=======
>>>>>>> b2277ad (ViewsTemplates)
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> f6d1e94 (ViewsTemplates)
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cantidad_personas', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_manager.cliente')),
=======
<<<<<<< HEAD
=======
>>>>>>> b2277ad (ViewsTemplates)
=======
>>>>>>> f6d1e94 (ViewsTemplates)
=======
>>>>>>> b2277ad (ViewsTemplates)
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('numPersonas', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('CONFIRMADA', 'CONFIRMADA'), ('CANCELADA', 'CANCELADA')], max_length=20)),
                ('total_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.cuenta')),
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> b2277ad (ViewsTemplates)
=======
=======
>>>>>>> f6d1e94 (ViewsTemplates)
>>>>>>> b2277ad (ViewsTemplates)
=======
>>>>>>> b2277ad (ViewsTemplates)
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manager.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manager.habitacion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_manager.reserva')),
            ],
        ),
    ]
