# Generated by Django 5.0.6 on 2024-06-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0004_reserva_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='servicios',
        ),
    ]
