# Generated by Django 5.0.6 on 2024-06-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0006_reserva_total_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='total_costo',
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.ManyToManyField(to='reservation_manager.servicio'),
        ),
    ]
