# Generated by Django 5.0.6 on 2024-06-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHotel', '0002_remove_personalhotel_persona_ptr_and_more'),
        ('client_manager', '0003_remove_cliente_persona_ptr_cliente_apellido_and_more'),
        ('core', '0003_alter_persona_documento_alter_persona_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
